services:
  app:
    build:
      context: ./
      args:
        - ENVIRONMENT=DEV
    image: latest-build
    restart: "unless-stopped"
    env_file: ".env"
    environment:
      - "INVENIO_BROKER_URL=${INVENIO_AMQP_BROKER_PROTOCOL}://${INVENIO_AMQP_BROKER_USER}:${INVENIO_AMQP_BROKER_PASSWORD}@${INVENIO_AMQP_BROKER_HOST}:${INVENIO_AMQP_BROKER_PORT}/${INVENIO_AMQP_BROKER_VHOST}"
      - "INVENIO_CELERY_BROKER_URL=${INVENIO_AMQP_BROKER_PROTOCOL}://${INVENIO_AMQP_BROKER_USER}:${INVENIO_AMQP_BROKER_PASSWORD}@${INVENIO_AMQP_BROKER_HOST}:${INVENIO_AMQP_BROKER_PORT}/${INVENIO_AMQP_BROKER_VHOST}"
      - "INVENIO_CACHE_TYPE=redis"
      - "INVENIO_CACHE_REDIS_URL=${INVENIO_KV_CACHE_PROTOCOL}://${INVENIO_KV_CACHE_PASSWORD:-''}${INVENIO_KV_CACHE_HOST}:${INVENIO_KV_CACHE_PORT}/0"
      - "INVENIO_ACCOUNTS_SESSION_REDIS_URL=${INVENIO_KV_CACHE_PROTOCOL}://${INVENIO_KV_CACHE_PASSWORD:-''}${INVENIO_KV_CACHE_HOST}:${INVENIO_KV_CACHE_PORT}/1"
      - "INVENIO_CELERY_RESULT_BACKEND=${INVENIO_KV_CACHE_PROTOCOL}://${INVENIO_KV_CACHE_PASSWORD:-''}${INVENIO_KV_CACHE_HOST}:${INVENIO_KV_CACHE_PORT}/2"
      - "INVENIO_RATELIMIT_STORAGE_URL=${INVENIO_KV_CACHE_PROTOCOL}://${INVENIO_KV_CACHE_PASSWORD:-''}${INVENIO_KV_CACHE_HOST}:${INVENIO_KV_CACHE_PORT}/3"
      - "INVENIO_COMMUNITIES_IDENTITIES_REDIS_URL=${INVENIO_KV_CACHE_PROTOCOL}://${INVENIO_KV_CACHE_PASSWORD:-''}${INVENIO_KV_CACHE_HOST}:${INVENIO_KV_CACHE_PORT}/4"
      - "INVENIO_SEARCH_HOSTS=['search:9200']"
      - "INVENIO_SECRET_KEY=CHANGE_ME"
      - "INVENIO_SQLALCHEMY_DATABASE_URI=${INVENIO_DB_PROTOCOL}://${INVENIO_DB_USER}:${INVENIO_DB_PASSWORD}@${INVENIO_DB_HOST}/${INVENIO_DB_NAME}"
      - "INVENIO_WSGI_PROXIES=2"
  frontend:
    build: ./docker/nginx/
    image: latest-build-frontend
    restart: "unless-stopped"
    ports:
      - "80"
      - "443"
  cache:
    image: redis:7
    restart: "unless-stopped"
    read_only: true
    env_file: ".env"
    ports:
      - "${CACHE_REDIS_PORT:-6379}:6379"
    environment:
      - "REDIS_USER=${INVENIO_KV_CACHE_USER}"
      - "REDIS_PASSWORD=${INVENIO_KV_CACHE_PASSWORD:-''}"
    command: >
      redis-server --requirepass ${INVENIO_KV_CACHE_PASSWORD:-''}
  db:
    image: postgres:14.0
    restart: "unless-stopped"
    env_file: ".env"
    environment:
      - "POSTGRES_USER=${INVENIO_DB_USER:-latest-build}"
      - "POSTGRES_PASSWORD=${INVENIO_DB_PASSWORD:-latest-build}"
      - "POSTGRES_DB=${INVENIO_DB_NAME:-latest-build}"
    ports:
      - "${INVENIO_DB_PORT:-5432}:5432"
  pgadmin:
    image: dpage/pgadmin4:6
    restart: "unless-stopped"
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "info@latest-build.com"
      PGADMIN_DEFAULT_PASSWORD: "latest-build"
    volumes:
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
  mq:
    image: rabbitmq:3-management
    restart: "unless-stopped"
    env_file: ".env"
    ports:
      - "15672:15672"
      - "${INVENIO_AMQP_BROKER_PORT:-5672}:5672"
    environment:
      - "RABBITMQ_DEFAULT_USER=${INVENIO_AMQP_BROKER_USER:-guest}"
      - "RABBITMQ_DEFAULT_PASS=${INVENIO_AMQP_BROKER_PASSWORD:-guest}"
  search:
    image: opensearchproject/opensearch:2.16.0
    restart: "unless-stopped"
    environment:
      # settings only for development. DO NOT use in production!
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=guekxe3mvqiekeforTESTINGOnly"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2g
    ports:
      - "9200:9200"
      - "9600:9600"
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.16.0
    ports:
      - "5601:5601"
    expose:
      - "5601"
    environment:
      # settings only for development. DO NOT use in production!
      - 'OPENSEARCH_HOSTS=["http://search:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
