flowchart LR
  flask_resources["flask-resources"] --> invenio_records_resources["invenio-records-resources"]
  invenio_access["invenio-access"] --> invenio_app_rdm["invenio-app-rdm"]
  invenio_access["invenio-access"] --> invenio_records_permissions["invenio-records-permissions"]
  invenio_accounts["invenio-accounts"] --> invenio_access["invenio-access"]
  invenio_accounts["invenio-accounts"] --> invenio_administration["invenio-administration"]
  invenio_accounts["invenio-accounts"] --> invenio_app_rdm["invenio-app-rdm"]
  invenio_accounts["invenio-accounts"] --> invenio_audit_logs["invenio-audit-logs"]
  invenio_accounts["invenio-accounts"] --> invenio_files_rest["invenio-files-rest"]
  invenio_accounts["invenio-accounts"] --> invenio_oauth2server["invenio-oauth2server"]
  invenio_accounts["invenio-accounts"] --> invenio_oauthclient["invenio-oauthclient"]
  invenio_accounts["invenio-accounts"] --> invenio_records_resources["invenio-records-resources"]
  invenio_accounts["invenio-accounts"] --> invenio_userprofiles["invenio-userprofiles"]
  invenio_accounts["invenio-accounts"] --> invenio_users_resources["invenio-users-resources"]
  invenio_administration["invenio-administration"] --> invenio_audit_logs["invenio-audit-logs"]
  invenio_administration["invenio-administration"] --> invenio_banners["invenio-banners"]
  invenio_administration["invenio-administration"] --> invenio_collections["invenio-collections"]
  invenio_administration["invenio-administration"] --> invenio_communities["invenio-communities"]
  invenio_administration["invenio-administration"] --> invenio_jobs["invenio-jobs"]
  invenio_administration["invenio-administration"] --> invenio_pages["invenio-pages"]
  invenio_administration["invenio-administration"] --> invenio_rdm_records["invenio-rdm-records"]
  invenio_administration["invenio-administration"] --> invenio_users_resources["invenio-users-resources"]
  invenio_administration["invenio-administration"] --> invenio_vocabularies["invenio-vocabularies"]
  invenio_app["invenio-app"] --> invenio_app_rdm["invenio-app-rdm"]
  invenio_assets["invenio-assets"] --> invenio_app_rdm["invenio-app-rdm"]
  invenio_assets["invenio-assets"] --> invenio_previewer["invenio-previewer"]
  invenio_assets["invenio-assets"] --> invenio_search_ui["invenio-search-ui"]
  invenio_assets["invenio-assets"] --> invenio_theme["invenio-theme"]
  invenio_audit_logs["invenio-audit-logs"] --> invenio_app_rdm["invenio-app-rdm"]
  invenio_audit_logs["invenio-audit-logs"] --> invenio_drafts_resources["invenio-drafts-resources"]
  invenio_audit_logs["invenio-audit-logs"] --> invenio_rdm_records["invenio-rdm-records"]
  invenio_banners["invenio-banners"] --> invenio_app_rdm["invenio-app-rdm"]
  invenio_base["invenio-base"] --> invenio_access["invenio-access"]
  invenio_base["invenio-base"] --> invenio_administration["invenio-administration"]
  invenio_base["invenio-base"] --> invenio_app["invenio-app"]
  invenio_base["invenio-base"] --> invenio_app_rdm["invenio-app-rdm"]
  invenio_base["invenio-base"] --> invenio_assets["invenio-assets"]
  invenio_base["invenio-base"] --> invenio_audit_logs["invenio-audit-logs"]
  invenio_base["invenio-base"] --> invenio_cache["invenio-cache"]
  invenio_base["invenio-base"] --> invenio_celery["invenio-celery"]
  invenio_base["invenio-base"] --> invenio_checks["invenio-checks"]
  invenio_base["invenio-base"] --> invenio_config["invenio-config"]
  invenio_base["invenio-base"] --> invenio_db["invenio-db"]
  invenio_base["invenio-base"] --> invenio_formatter["invenio-formatter"]
  invenio_base["invenio-base"] --> invenio_i18n["invenio-i18n"]
  invenio_base["invenio-base"] --> invenio_jobs["invenio-jobs"]
  invenio_base["invenio-base"] --> invenio_jsonschemas["invenio-jsonschemas"]
  invenio_base["invenio-base"] --> invenio_notifications["invenio-notifications"]
  invenio_base["invenio-base"] --> invenio_oaiserver["invenio-oaiserver"]
  invenio_base["invenio-base"] --> invenio_oauth2server["invenio-oauth2server"]
  invenio_base["invenio-base"] --> invenio_oauthclient["invenio-oauthclient"]
  invenio_base["invenio-base"] --> invenio_pages["invenio-pages"]
  invenio_base["invenio-base"] --> invenio_pidstore["invenio-pidstore"]
  invenio_base["invenio-base"] --> invenio_previewer["invenio-previewer"]
  invenio_base["invenio-base"] --> invenio_queues["invenio-queues"]
  invenio_base["invenio-base"] --> invenio_rdm_records["invenio-rdm-records"]
  invenio_base["invenio-base"] --> invenio_records_files["invenio-records-files"]
  invenio_base["invenio-base"] --> invenio_records_resources["invenio-records-resources"]
  invenio_base["invenio-base"] --> invenio_records_rest["invenio-records-rest"]
  invenio_base["invenio-base"] --> invenio_records_ui["invenio-records-ui"]
  invenio_base["invenio-base"] --> invenio_rest["invenio-rest"]
  invenio_base["invenio-base"] --> invenio_search["invenio-search"]
  invenio_base["invenio-base"] --> invenio_search_ui["invenio-search-ui"]
  invenio_base["invenio-base"] --> invenio_sitemap["invenio-sitemap"]
  invenio_base["invenio-base"] --> invenio_stats["invenio-stats"]
  invenio_base["invenio-base"] --> invenio_theme["invenio-theme"]
  invenio_base["invenio-base"] --> invenio_users_resources["invenio-users-resources"]
  invenio_cache["invenio-cache"] --> invenio_app["invenio-app"]
  invenio_cache["invenio-cache"] --> invenio_app_rdm["invenio-app-rdm"]
  invenio_cache["invenio-cache"] --> invenio_sitemap["invenio-sitemap"]
  invenio_cache["invenio-cache"] --> invenio_stats["invenio-stats"]
  invenio_celery["invenio-celery"] --> invenio_accounts["invenio-accounts"]
  invenio_celery["invenio-celery"] --> invenio_app["invenio-app"]
  invenio_celery["invenio-celery"] --> invenio_app_rdm["invenio-app-rdm"]
  invenio_celery["invenio-celery"] --> invenio_jobs["invenio-jobs"]
  invenio_celery["invenio-celery"] --> invenio_logging["invenio-logging"]
  invenio_celery["invenio-celery"] --> invenio_queues["invenio-queues"]
  invenio_celery["invenio-celery"] --> invenio_records["invenio-records"]
  invenio_celery["invenio-celery"] --> invenio_sitemap["invenio-sitemap"]
  invenio_celery["invenio-celery"] --> invenio_stats["invenio-stats"]
  invenio_checks["invenio-checks"] --> invenio_rdm_records["invenio-rdm-records"]
  invenio_collections["invenio-collections"] --> invenio_app_rdm["invenio-app-rdm"]
  invenio_collections["invenio-collections"] --> invenio_communities["invenio-communities"]
  invenio_collections["invenio-collections"] --> invenio_rdm_records["invenio-rdm-records"]
  invenio_communities["invenio-communities"] --> invenio_app_rdm["invenio-app-rdm"]
  invenio_communities["invenio-communities"] --> invenio_checks["invenio-checks"]
  invenio_communities["invenio-communities"] --> invenio_rdm_records["invenio-rdm-records"]
  invenio_config["invenio-config"] --> invenio_app["invenio-app"]
  invenio_config["invenio-config"] --> invenio_app_rdm["invenio-app-rdm"]
  invenio_db["invenio-db"] --> invenio_administration["invenio-administration"]
  invenio_db["invenio-db"] --> invenio_app_rdm["invenio-app-rdm"]
  invenio_db["invenio-db"] --> invenio_indexer["invenio-indexer"]
  invenio_db["invenio-db"] --> invenio_logging["invenio-logging"]
  invenio_db["invenio-db"] --> invenio_records_resources["invenio-records-resources"]
  invenio_drafts_resources["invenio-drafts-resources"] --> invenio_checks["invenio-checks"]
  invenio_drafts_resources["invenio-drafts-resources"] --> invenio_rdm_records["invenio-rdm-records"]
  invenio_files_rest["invenio-files-rest"] --> invenio_app_rdm["invenio-app-rdm"]
  invenio_files_rest["invenio-files-rest"] --> invenio_records_files["invenio-records-files"]
  invenio_files_rest["invenio-files-rest"] --> invenio_records_resources["invenio-records-resources"]
  invenio_files_rest["invenio-files-rest"] --> invenio_s3["invenio-s3"]
  invenio_formatter["invenio-formatter"] --> invenio_app_rdm["invenio-app-rdm"]
  invenio_formatter["invenio-formatter"] --> invenio_previewer["invenio-previewer"]
  invenio_i18n["invenio-i18n"] --> invenio_access["invenio-access"]
  invenio_i18n["invenio-i18n"] --> invenio_accounts["invenio-accounts"]
  invenio_i18n["invenio-i18n"] --> invenio_administration["invenio-administration"]
  invenio_i18n["invenio-i18n"] --> invenio_app_rdm["invenio-app-rdm"]
  invenio_i18n["invenio-i18n"] --> invenio_audit_logs["invenio-audit-logs"]
  invenio_i18n["invenio-i18n"] --> invenio_banners["invenio-banners"]
  invenio_i18n["invenio-i18n"] --> invenio_checks["invenio-checks"]
  invenio_i18n["invenio-i18n"] --> invenio_drafts_resources["invenio-drafts-resources"]
  invenio_i18n["invenio-i18n"] --> invenio_files_rest["invenio-files-rest"]
  invenio_i18n["invenio-i18n"] --> invenio_formatter["invenio-formatter"]
  invenio_i18n["invenio-i18n"] --> invenio_jobs["invenio-jobs"]
  invenio_i18n["invenio-i18n"] --> invenio_notifications["invenio-notifications"]
  invenio_i18n["invenio-i18n"] --> invenio_oaiserver["invenio-oaiserver"]
  invenio_i18n["invenio-i18n"] --> invenio_oauth2server["invenio-oauth2server"]
  invenio_i18n["invenio-i18n"] --> invenio_oauthclient["invenio-oauthclient"]
  invenio_i18n["invenio-i18n"] --> invenio_pidstore["invenio-pidstore"]
  invenio_i18n["invenio-i18n"] --> invenio_previewer["invenio-previewer"]
  invenio_i18n["invenio-i18n"] --> invenio_rdm_records["invenio-rdm-records"]
  invenio_i18n["invenio-i18n"] --> invenio_records["invenio-records"]
  invenio_i18n["invenio-i18n"] --> invenio_records_resources["invenio-records-resources"]
  invenio_i18n["invenio-i18n"] --> invenio_records_rest["invenio-records-rest"]
  invenio_i18n["invenio-i18n"] --> invenio_records_ui["invenio-records-ui"]
  invenio_i18n["invenio-i18n"] --> invenio_search_ui["invenio-search-ui"]
  invenio_i18n["invenio-i18n"] --> invenio_stats["invenio-stats"]
  invenio_i18n["invenio-i18n"] --> invenio_theme["invenio-theme"]
  invenio_i18n["invenio-i18n"] --> invenio_userprofiles["invenio-userprofiles"]
  invenio_i18n["invenio-i18n"] --> invenio_users_resources["invenio-users-resources"]
  invenio_i18n["invenio-i18n"] --> invenio_vocabularies["invenio-vocabularies"]
  invenio_indexer["invenio-indexer"] --> invenio_app_rdm["invenio-app-rdm"]
  invenio_indexer["invenio-indexer"] --> invenio_audit_logs["invenio-audit-logs"]
  invenio_indexer["invenio-indexer"] --> invenio_records_resources["invenio-records-resources"]
  invenio_indexer["invenio-indexer"] --> invenio_records_rest["invenio-records-rest"]
  invenio_jobs["invenio-jobs"] --> invenio_rdm_records["invenio-rdm-records"]
  invenio_jobs["invenio-jobs"] --> invenio_vocabularies["invenio-vocabularies"]
  invenio_jsonschemas["invenio-jsonschemas"] --> invenio_app_rdm["invenio-app-rdm"]
  invenio_jsonschemas["invenio-jsonschemas"] --> invenio_records_resources["invenio-records-resources"]
  invenio_logging["invenio-logging"] --> invenio_app_rdm["invenio-app-rdm"]
  invenio_logging["invenio-logging"] --> invenio_rest["invenio-rest"]
  invenio_mail["invenio-mail"] --> invenio_accounts["invenio-accounts"]
  invenio_mail["invenio-mail"] --> invenio_app_rdm["invenio-app-rdm"]
  invenio_mail["invenio-mail"] --> invenio_oauthclient["invenio-oauthclient"]
  invenio_notifications["invenio-notifications"] --> invenio_users_resources["invenio-users-resources"]
  invenio_oaiserver["invenio-oaiserver"] --> invenio_app_rdm["invenio-app-rdm"]
  invenio_oaiserver["invenio-oaiserver"] --> invenio_communities["invenio-communities"]
  invenio_oaiserver["invenio-oaiserver"] --> invenio_rdm_records["invenio-rdm-records"]
  invenio_oauth2server["invenio-oauth2server"] --> invenio_app_rdm["invenio-app-rdm"]
  invenio_oauth2server["invenio-oauth2server"] --> invenio_rdm_records["invenio-rdm-records"]
  invenio_oauthclient["invenio-oauthclient"] --> invenio_app_rdm["invenio-app-rdm"]
  invenio_oauthclient["invenio-oauthclient"] --> invenio_users_resources["invenio-users-resources"]
  invenio_pages["invenio-pages"] --> invenio_app_rdm["invenio-app-rdm"]
  invenio_pidstore["invenio-pidstore"] --> invenio_app_rdm["invenio-app-rdm"]
  invenio_pidstore["invenio-pidstore"] --> invenio_indexer["invenio-indexer"]
  invenio_pidstore["invenio-pidstore"] --> invenio_oaiserver["invenio-oaiserver"]
  invenio_pidstore["invenio-pidstore"] --> invenio_previewer["invenio-previewer"]
  invenio_pidstore["invenio-pidstore"] --> invenio_records_resources["invenio-records-resources"]
  invenio_pidstore["invenio-pidstore"] --> invenio_records_rest["invenio-records-rest"]
  invenio_pidstore["invenio-pidstore"] --> invenio_records_ui["invenio-records-ui"]
  invenio_previewer["invenio-previewer"] --> invenio_app_rdm["invenio-app-rdm"]
  invenio_queues["invenio-queues"] --> invenio_stats["invenio-stats"]
  invenio_rdm_records["invenio-rdm-records"] --> invenio_app_rdm["invenio-app-rdm"]
  invenio_records["invenio-records"] --> invenio_app_rdm["invenio-app-rdm"]
  invenio_records["invenio-records"] --> invenio_indexer["invenio-indexer"]
  invenio_records["invenio-records"] --> invenio_oaiserver["invenio-oaiserver"]
  invenio_records["invenio-records"] --> invenio_records_files["invenio-records-files"]
  invenio_records["invenio-records"] --> invenio_records_resources["invenio-records-resources"]
  invenio_records["invenio-records"] --> invenio_records_rest["invenio-records-rest"]
  invenio_records["invenio-records"] --> invenio_records_ui["invenio-records-ui"]
  invenio_records_files["invenio-records-files"] --> invenio_app_rdm["invenio-app-rdm"]
  invenio_records_permissions["invenio-records-permissions"] --> invenio_records_resources["invenio-records-resources"]
  invenio_records_resources["invenio-records-resources"] --> invenio_administration["invenio-administration"]
  invenio_records_resources["invenio-records-resources"] --> invenio_audit_logs["invenio-audit-logs"]
  invenio_records_resources["invenio-records-resources"] --> invenio_banners["invenio-banners"]
  invenio_records_resources["invenio-records-resources"] --> invenio_collections["invenio-collections"]
  invenio_records_resources["invenio-records-resources"] --> invenio_communities["invenio-communities"]
  invenio_records_resources["invenio-records-resources"] --> invenio_drafts_resources["invenio-drafts-resources"]
  invenio_records_resources["invenio-records-resources"] --> invenio_jobs["invenio-jobs"]
  invenio_records_resources["invenio-records-resources"] --> invenio_pages["invenio-pages"]
  invenio_records_resources["invenio-records-resources"] --> invenio_rdm_records["invenio-rdm-records"]
  invenio_records_resources["invenio-records-resources"] --> invenio_requests["invenio-requests"]
  invenio_records_resources["invenio-records-resources"] --> invenio_users_resources["invenio-users-resources"]
  invenio_records_resources["invenio-records-resources"] --> invenio_vocabularies["invenio-vocabularies"]
  invenio_records_rest["invenio-records-rest"] --> invenio_app_rdm["invenio-app-rdm"]
  invenio_records_rest["invenio-records-rest"] --> invenio_records_files["invenio-records-files"]
  invenio_records_ui["invenio-records-ui"] --> invenio_app_rdm["invenio-app-rdm"]
  invenio_records_ui["invenio-records-ui"] --> invenio_previewer["invenio-previewer"]
  invenio_requests["invenio-requests"] --> invenio_communities["invenio-communities"]
  invenio_rest["invenio-rest"] --> invenio_accounts["invenio-accounts"]
  invenio_rest["invenio-rest"] --> invenio_app_rdm["invenio-app-rdm"]
  invenio_rest["invenio-rest"] --> invenio_oaiserver["invenio-oaiserver"]
  invenio_rest["invenio-rest"] --> invenio_pages["invenio-pages"]
  invenio_rest["invenio-rest"] --> invenio_records_rest["invenio-records-rest"]
  invenio_search_ui["invenio-search-ui"] --> invenio_administration["invenio-administration"]
  invenio_search_ui["invenio-search-ui"] --> invenio_app_rdm["invenio-app-rdm"]
  invenio_search_ui["invenio-search-ui"] --> invenio_collections["invenio-collections"]
  invenio_search_ui["invenio-search-ui"] --> invenio_communities["invenio-communities"]
  invenio_sitemap["invenio-sitemap"] --> invenio_app_rdm["invenio-app-rdm"]
  invenio_stats["invenio-stats"] --> invenio_rdm_records["invenio-rdm-records"]
  invenio_stats["invenio-stats"] --> invenio_records_resources["invenio-records-resources"]
  invenio_theme["invenio-theme"] --> invenio_accounts["invenio-accounts"]
  invenio_theme["invenio-theme"] --> invenio_administration["invenio-administration"]
  invenio_theme["invenio-theme"] --> invenio_app_rdm["invenio-app-rdm"]
  invenio_theme["invenio-theme"] --> invenio_oauth2server["invenio-oauth2server"]
  invenio_theme["invenio-theme"] --> invenio_oauthclient["invenio-oauthclient"]
  invenio_theme["invenio-theme"] --> invenio_requests["invenio-requests"]
  invenio_userprofiles["invenio-userprofiles"] --> invenio_app_rdm["invenio-app-rdm"]
  invenio_users_resources["invenio-users-resources"] --> invenio_jobs["invenio-jobs"]
  invenio_users_resources["invenio-users-resources"] --> invenio_requests["invenio-requests"]
  invenio_vocabularies["invenio-vocabularies"] --> invenio_communities["invenio-communities"]
  invenio_vocabularies["invenio-vocabularies"] --> invenio_rdm_records["invenio-rdm-records"]
  marshmallow["marshmallow"] --> flask_resources["flask-resources"]
  marshmallow["marshmallow"] --> invenio_rest["invenio-rest"]
  marshmallow["marshmallow"] --> marshmallow_oneofschema["marshmallow-oneofschema"]
  marshmallow["marshmallow"] --> marshmallow_utils["marshmallow-utils"]
  marshmallow_oneofschema["marshmallow-oneofschema"] --> marshmallow_utils["marshmallow-utils"]
  marshmallow_utils["marshmallow-utils"] --> invenio_files_rest["invenio-files-rest"]
  marshmallow_utils["marshmallow-utils"] --> invenio_records_resources["invenio-records-resources"]
  marshmallow_utils["marshmallow-utils"] --> invenio_records_rest["invenio-records-rest"]
  marshmallow_utils["marshmallow-utils"] --> invenio_rest["invenio-rest"]
